package kr.co.manager.exception.rdb;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import kr.co.manager.domain.jpa.AlarmStatus;

@Repository
public interface AlarmStatusRepository extends JpaRepository<AlarmStatus, Integer>{
	
//	@Query(nativeQuery = true, value = "SELECT distinct alarm_id FROM alarm_status WHERE machine_id = :machineId AND reg_date > :startDate AND reg_date < :endDate ;")
//	List<Integer> userFindAlarmIdByMachineIdAndRegDate(@Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate);
	
	// alarm chart time data
//	@Query(nativeQuery = true, value = "SELECT                                                                                                                                                                                                               \r\n" +
//			"    ast.machine_id, ast.reg_date, ast.update_date, ast.alarm_id, ast.alarm_type, ast.alarm_no, ast.alarm_axis, ast.alarm_msg, sum(ast.holding_time) as total_holding_time, count(*) as cnt, date_format(ast.reg_date, '%Y-%m-%d') as date     \r\n" +
//			"FROM                                                                                                                                                                                                                                            \r\n" +
//			"    factory f                                                                                                                                                                                                                                   \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                                                                 \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                                                                \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                                                              \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_status ast ON m.machine_id = ast.machine_id AND ast.reg_date > :startDate AND ast.reg_date < :endDate                                                                                                                                  \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_info ai ON ast.alarm_id = ai.alarm_id                                                                                                                                                                                                  \r\n" +
//			"WHERE                                                                                                                                                                                                                                           \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                                                                                    \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (a.area_id = :areaId OR :areaId = 1 OR :areaId IS NULL)                                                                                                                                                                                                                   \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (m.machine_id = :machineId OR 1 = 1 OR 1 IS NULL)                                                                                                                                                                                                                   \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                                                             \r\n" +
//			"GROUP BY                                                                                                                                                                                                                                        \r\n" +
//			"	m.machine_id, ast.alarm_id, date_format(ast.reg_date, '%Y-%m-%d')                                                                                                                                                                                          \r\n" +
//			"ORDER BY                                                                                                                                                                                                                                        \r\n" +
//			"	:filter desc, date                                                                                                                                                                                                                                         \r\n" +
//			";                                                                                                                                                                                                                                               \r\n")
//	List<Object[]> userFindAlarmDetailListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate, @Param("filter") String filter);
	
	// alarm chart cnt data
//	@Query(nativeQuery = true, value = "SELECT                                                                                                                                                                                                               \r\n" +
//			"    ast.machine_id, ast.reg_date, ast.update_date, ast.alarm_id, ast.alarm_type, ast.alarm_no, ast.alarm_axis, ai.alarm_msg_kr, sum(ast.holding_time) as total_holding_time, count(*) as cnt, date_format(ast.reg_date, '%Y-%m-%d') as date     \r\n" +
//			"FROM                                                                                                                                                                                                                                            \r\n" +
//			"    factory f                                                                                                                                                                                                                                   \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                                                                 \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                                                                \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                                                              \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_status ast ON m.machine_id = ast.machine_id AND ast.reg_date > :startDate AND ast.reg_date < :endDate                                                                                                                                  \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_info ai ON ast.alarm_id = ai.alarm_id                                                                                                                                                                                                  \r\n" +
//			"WHERE                                                                                                                                                                                                                                           \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                                                                                    \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (a.area_id = :areaId OR :areaId IS NULL)                                                                                                                                                                                                                   \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (m.machine_id = :machineId OR :machineId IS NULL)                                                                                                                                                                                                                   \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                                                             \r\n" +
//			"GROUP BY                                                                                                                                                                                                                                        \r\n" +
//			"	m.machine_id, ast.alarm_id, date_format(ast.reg_date, '%Y-%m-%d')                                                                                                                                                                                          \r\n" +
//			"ORDER BY                                                                                                                                                                                                                                        \r\n" +
//			"	cnt desc, date                                                                                                                                                                                                                                         \r\n" )
//	List<Object[]> userFindAlarmDetailCntListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate);
	
	// alarm chart time data
//	@Query(nativeQuery = true, value = "SELECT                                                                                                                                                                                                               \r\n" +
//			"    ast.machine_id, ast.reg_date, ast.update_date, ast.alarm_id, ast.alarm_type, ast.alarm_no, ast.alarm_axis, ast.alarm_msg, sum(ast.holding_time) as total_holding_time, count(*) as cnt, date_format(ast.reg_date, '%Y-%m-%d') as date, m.machine_name \r\n" +
//			"FROM                                                                                                                                                                                                                                            \r\n" +
//			"    factory f                                                                                                                                                                                                                                   \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                                                                 \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                                                                \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                                                              \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_status ast ON m.machine_id = ast.machine_id AND ast.reg_date > :startDate AND ast.reg_date < :endDate                                                                                                                                  \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_info ai ON ast.alarm_id = ai.alarm_id                                                                                                                                                                                                  \r\n" +
//			"WHERE                                                                                                                                                                                                                                           \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                                                                                    \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (a.area_id = :areaId OR :areaId IS NULL)                                                                                                                                                                                     \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (m.machine_id = :machineId OR :machineId IS NULL)                                                                                                                                                                                     \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                                                             \r\n" +
//			"GROUP BY                                                                                                                                                                                                                                        \r\n" +
//			"	m.machine_id, ast.alarm_id                                                                                                                                                                                                                   \r\n" +
//			"ORDER BY                                                                                                                                                                                                                                        \r\n" +
//			"	:filter desc, ast.alarm_id, date                                                                                                                                                                                                                                         \r\n" +
//			";                                                                                                                                                                                                                                               \r\n")
//	List<Object[]> userFindAlarmMsgListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate, @Param("filter") String filter);
	
	// alarm chart cnt data
//	@Query(nativeQuery = true, value = "SELECT                                                                                                                                                                                                               \r\n" +
//			"    ast.machine_id, ast.reg_date, ast.update_date, ast.alarm_id, ast.alarm_type, ast.alarm_no, ast.alarm_axis, ast.alarm_msg, sum(ast.holding_time) as total_holding_time, count(*) as cnt, date_format(ast.reg_date, '%Y-%m-%d') as date, m.machine_name \r\n" +
//			"FROM                                                                                                                                                                                                                                            \r\n" +
//			"    factory f                                                                                                                                                                                                                                   \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                                                                 \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                                                                \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                                                              \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_status ast ON m.machine_id = ast.machine_id AND ast.reg_date > :startDate AND ast.reg_date < :endDate                                                                                                                                  \r\n" +
//			"JOIN                                                                                                                                                                                                                                            \r\n" +
//			"	alarm_info ai ON ast.alarm_id = ai.alarm_id                                                                                                                                                                                                  \r\n" +
//			"WHERE                                                                                                                                                                                                                                           \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                                                                                    \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (a.area_id = :areaId OR :areaId = 1 OR :areaId IS NULL)                                                                                                                                                                                     \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    (m.machine_id = :machineId OR :machineId = 1 OR :machineId IS NULL)                                                                                                                                                                                     \r\n" +
//			"    AND                                                                                                                                                                                                                                         \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                                                             \r\n" +
//			"GROUP BY                                                                                                                                                                                                                                        \r\n" +
//			"	m.machine_id, ast.alarm_id                                                                                                                                                                                                                   \r\n" +
//			"ORDER BY                                                                                                                                                                                                                                        \r\n" +
//			"	cnt desc, ast.alarm_id, date                                                                                                                                                                                                                                         \r\n" +
//			";                                                                                                                                                                                                                                               \r\n")
//	List<Object[]> userFindAlarmMsgCntListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate);
	
//	@Query(nativeQuery = true, value = "SELECT                                                                                                                                              \r\n" +
//			"    a.area_id, a.area_name, m.machine_id, m.machine_name, ast.reg_date, ast.update_date, ast.alarm_id, ast.alarm_type, ast.alarm_no, ast.alarm_axis, ast.alarm_msg           \r\n" +
//			"FROM                                                                                                                                                                           \r\n" +
//			"    factory f                                                                                                                                                                  \r\n" +
//			"JOIN                                                                                                                                                                           \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                \r\n" +
//			"JOIN                                                                                                                                                                           \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                               \r\n" +
//			"JOIN                                                                                                                                                                           \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                             \r\n" +
//			"JOIN                                                                                                                                                                           \r\n" +
//			"	alarm_status ast ON m.machine_id = ast.machine_id AND ast.reg_date > :startDate AND ast.reg_date < :endDate                                                                 \r\n" +
//			"JOIN                                                                                                                                                                           \r\n" +
//			"	alarm_info ai ON ast.alarm_id = ai.alarm_id                                                                                                                                 \r\n" +
//			"WHERE                                                                                                                                                                          \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                   \r\n" +
//			"    AND                                                                                                                                                                        \r\n" +
//			"    (a.area_id = :areaId OR :areaId = 1 OR :areaId IS NULL)                                                                                                                    \r\n" +
//			"    AND                                                                                                                                                                        \r\n" +
//			"    (m.machine_id = :machineId OR :machineId = 1 OR :machineId IS NULL)                                                                                                        \r\n" +
//			"    AND                                                                                                                                                                        \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                            \r\n" +
//			"ORDER BY                                                                                                                                                                       \r\n" +
//			"	m.machine_id, ast.reg_date asc, update_date asc                                                                                                                             \r\n" +
//			";                                                                                                                                                                              \r\n")
//	List<Object[]> userFindAlarmHistoryByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate);
	
//	@Query(nativeQuery = true, value = "SELECT                                                                                             \r\n" + 
//			"    a.area_id, a.area_name, m.machine_id, m.machine_name, IF(sum(ast.holding_time) IS NULL, 0, count(*)) AS cnt               \r\n" +
//			"FROM                                                                                                                          \r\n" +
//			"    factory f                                                                                                                 \r\n" +
//			"JOIN                                                                                                                          \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                 \r\n" +
//			"JOIN                                                                                                                          \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                \r\n" +
//			"JOIN                                                                                                                          \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                              \r\n" +
//			"LEFT JOIN                                                                                                                     \r\n" +
//			"	alarm_status ast ON m.machine_id = ast.machine_id AND ast.reg_date > :startDate AND ast.reg_date < :endDate                  \r\n" +
//			"LEFT JOIN                                                                                                                     \r\n" +
//			"	alarm_info ai ON ast.alarm_id = ai.alarm_id                                                                                  \r\n" +
//			"WHERE                                                                                                                         \r\n" +
//			"	f.factory_id = :factoryId                                                                                                    \r\n" +
//			"    AND                                                                                                                       \r\n" +
//			"    (a.area_id = :areaId OR :areaId = 1 OR :areaId IS NULL)                                                                   \r\n" +
//			"	AND                                                                                                                          \r\n" +
//			"    (m.machine_id = :machineId OR :machineId = 1 OR :machineId IS NULL)                                                       \r\n" +
//			"    AND                                                                                                                       \r\n" +
//			"    m.view_yn = 'y'                                                                                                           \r\n" +
//			"GROUP BY                                                                                                                      \r\n" +
//			"	m.machine_id                                                                                                                 \r\n" +
//			"ORDER BY                                                                                                                      \r\n" +
//			"	cnt desc                                                                                                                 \r\n" +
//			";                                                                                                                             \r\n")
//	List<Object[]> userFindAlarmMachineCntListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate);
}
