package kr.co.manager.exception.rdb;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import kr.co.manager.domain.jpa.AlarmEventStatus;

@Repository
public interface AlarmEventStatusRepository extends JpaRepository<AlarmEventStatus, Integer>{
	
	// 설비별 검색 차트 데이터
	// qeurydsl로 변경하여 주석 처리
//	@Query(nativeQuery = true, value = 
//			" SELECT                                                                                                                                   \r\n " +
//			"     a.area_id, a.area_name, m.machine_id, m.machine_name, SUM(aes.holding_time) AS total_holding_time , IF(sum(aes.holding_time) IS NULL, 0, count(*)) AS cnt, aes.alarm_id, aes.alarm_msg   \r\n " +
//			" FROM                                                                                                                                     \r\n " +
//			"     factory f                                                                                                                            \r\n " +
//			" JOIN                                                                                                                                     \r\n " +
//			" 	  qg_client qc ON f.factory_id = qc.factory_id                                                                                         \r\n " +
//			" JOIN                                                                                                                                     \r\n " +
//			" 	  machine m ON qc.qg_client_id = m.qg_client_id                                                                                        \r\n " +
//			" JOIN                                                                                                                                     \r\n " +
//			" 	  area a ON m.area_id = a.area_id                                                                                                      \r\n " +
//			" LEFT JOIN                                                                                                                                \r\n " +
//			" 	  alarm_event_status aes ON m.machine_id = aes.machine_id AND aes.reg_date > :startDate AND aes.reg_date < :endDate AND (aes.alarm_type_id = :alarmType OR :alarmType IS NULL) AND aes.update_date IS NOT NULL                    \r\n " +
//			" JOIN                                                                                                                                     \r\n " +
//			" 	  alarm_dictionary ad ON aes.alarm_id = ad.alarm_id AND ad.use_yn = 'y'                                                                                                      \r\n " +
//			" JOIN                                                                                                                                     \r\n " +
//			" 	  alarm_type atp ON ad.alarm_type_id = atp.alarm_type_id AND atp.use_yn = 'y'                                                                                                      \r\n " +
//			" WHERE                                                                                                                                    \r\n " +
//			" 	  f.factory_id = :factoryId                                                                                                                     \r\n " +
//			"     AND                                                                                                                                  \r\n " +
//			"     (a.area_id = :areaId OR :areaId IS NULL)                                                                              \r\n " +
//			"     AND                                                                                                                                  \r\n " +
//			"     (m.machine_id = :machineId OR :machineId IS NULL)                                                                  \r\n " +
//			"     AND                                                                                                                                  \r\n " +
//			"     m.view_yn = 'y'                                                                                                                      \r\n " +
//			" GROUP BY CASE WHEN                                                                                                                                 \r\n " +
//			" 	  'machineId' = :groupBy THEN m.machine_id                                                                                                                         \r\n " +
//			" 	  ELSE aes.alarm_id                                                                                                                         \r\n " +
//			" 	  END                                                                                                                         \r\n " +
//			" ORDER BY                                                                                                                                 \r\n " +
//			" 	  :filter desc                                                                                                           \r\n " +
//			" ;                                                                                                                                        \r\n ")
//	List<Object[]> userFindAlarmMachineCntListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate, @Param("filter") String filter, @Param("alarmType") Integer alarmType,@Param("groupBy") String groupBy);
	
	// 알람유형별 검색 차트 데이터
	@Query(nativeQuery = true, value = "SELECT distinct alarm_id FROM alarm_event_status WHERE machine_id = :machineId AND reg_date > :startDate AND reg_date < :endDate AND update_date IS NOT NULL ;")
	List<Integer> userFindAlarmIdByMachineIdAndRegDate(@Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate);
	
	// qeurydsl로 변경하여 주석 처리
//	@Query(nativeQuery = true, value = 
//			"SELECT                                                                                                                                                                                                                                                                                     \r\n" +
//			"    aes.machine_id, aes.reg_date, aes.update_date, aes.alarm_id, aes.machine_alarm_type, aes.machine_alarm_no, aes.machine_alarm_axis, aes.alarm_msg, sum(aes.holding_time) as total_holding_time, IF(SUM(aes.holding_time) IS NULL, 0, COUNT(*)) AS cnt, date_format(aes.reg_date, '%Y-%m-%d') as date, aes.alarm_type_id, atp.alarm_type, m.machine_name       \r\n" +
//			"FROM                                                                                                                                                                                                                                                                                       \r\n" +
//			"    factory f                                                                                                                                                                                                                                                                              \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                       \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                                                                                                              \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                       \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                                                                                                             \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                       \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                                                                                                           \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                       \r\n" +
//			"	alarm_event_status aes ON m.machine_id = aes.machine_id AND aes.reg_date > :startDate AND aes.reg_date < :endDate AND aes.update_date IS NOT NULL                                                                                                                                                                         \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                       \r\n" +
//			"	alarm_dictionary ad ON aes.alarm_id = ad.alarm_id AND (ad.alarm_id = :alarmId OR :alarmId IS NULL)                                                                                                                                                                                                                                         \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                       \r\n" +
//			"	alarm_type atp ON ad.alarm_type_id = atp.alarm_type_id                                                                                                                                                                                                                                         \r\n" +
//			"WHERE                                                                                                                                                                                                                                                                                      \r\n" +
//			"	 f.factory_id = :factoryId                                                                                                                                                                                                                                                                          \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                    \r\n" +
//			"    (a.area_id = :areaId OR :areaId IS NULL)                                                                                                                                                                                                                                \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                    \r\n" +
//			"    (m.machine_id = :machineId OR :machineId IS NULL)                                                                                                                                                                                                                                      \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                    \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                                                                                                        \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                    \r\n" +
//			"    atp.use_yn = 'y'                                                                                                                                                                                                                                                                        \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                    \r\n" +
//			"    ad.use_yn = 'y'                                                                                                                                                                                                                                                                        \r\n" +
//			"GROUP BY                                                                                                                                                                                                                                                                                   \r\n" +
//			"	m.machine_id, aes.alarm_id, date_format(aes.reg_date, '%Y-%m-%d')                                                                                                                                                                                                                         \r\n" +
//			"ORDER BY                                                                                                                                                                                                                                                                                   \r\n" +
//			"	:filter desc, date                                                                                                                                                                                                                                                                        \r\n" +
//			";")
//	List<Object[]> userFindAlarmDetailListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate, @Param("filter") String filter, @Param("alarmId") Integer alarmId);
	
	// 설비별, 알람별 검색 차트 2단계 데이터
	// qeurydsl로 변경하여 주석 처리
//	@Query(nativeQuery = true, value = 
//			"SELECT                                                                                                                                                                                                                                                                                    \r\n" +
//			"    aes.machine_id, aes.reg_date, aes.update_date, aes.alarm_id, aes.machine_alarm_type, aes.machine_alarm_no, aes.machine_alarm_axis, aes.alarm_msg, sum(aes.holding_time) as total_holding_time, count(*) as cnt, date_format(aes.reg_date, '%Y-%m-%d') as date, m.machine_name         \r\n" +
//			"FROM                                                                                                                                                                                                                                                                                      \r\n" +
//			"    factory f                                                                                                                                                                                                                                                                             \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                      \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                                                                                                             \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                      \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                                                                                                            \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                      \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                                                                                                          \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                      \r\n" +
//			"	alarm_event_status aes ON m.machine_id = aes.machine_id AND aes.reg_date > :startDate AND aes.reg_date < :endDate AND aes.update_date IS NOT NULL                                                                                                                                                                        \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                      \r\n" +
//			"	alarm_dictionary ad ON aes.alarm_id = ad.alarm_id AND ad.use_yn = 'y'                                                                                                                                                                                                                    \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                                      \r\n" +
//			"	alarm_type atp ON ad.alarm_type_id = atp.alarm_type_id AND atp.use_yn = 'y'                                                                                                                                                                                                              \r\n" +
//			"WHERE                                                                                                                                                                                                                                                                                     \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                                                                                                                                 \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                   \r\n" +
//			"    (a.area_id = :areaId OR :areaId IS NULL)                                                                                                                                                                                                                                              \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                   \r\n" +
//			"    (m.machine_id = :machineId OR :machineId IS NULL)                                                                                                                                                                                                                                     \r\n" +
//			"    AND                                                                                                                                                                                                                                                                                   \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                                                                                                       \r\n" +
//			"GROUP BY CASE WHEN                                                                                                                                                                                                                                                                                  \r\n" +
//			" 	  'machineId' = :groupBy THEN m.machine_id                                                                                                                         \r\n " +
//			" 	  ELSE aes.alarm_id END                                                                                                                         \r\n " +
//			" 	  , CASE WHEN                                                                                                                         \r\n " +
//			" 	  'machineId' = :groupBy THEN aes.alarm_id                                                                                                                         \r\n " +
//			" 	  ELSE m.machine_id END                                                                                                                         \r\n " +
//			"ORDER BY                                                                                                                                                                                                                                                                                  \r\n" +
//			"	:filter desc, aes.alarm_id, date                                                                                                                                                                                                                                                         \r\n" +
//			";                                                                                                                                                                                                                                                                                         \r\n")
//	List<Object[]> userFindAlarmMsgListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate, @Param("filter") String filter, @Param("groupBy") String groupBy);
	
	// 알람유형별 검색 차트 2단계 데이터
	// qeurydsl로 변경하여 주석 처리
//	@Query(nativeQuery = true, value = 
//			"SELECT                                                                                                                                                                                                                                                                 \r\n" +
//			"    aes.machine_id, aes.reg_date, aes.update_date, aes.alarm_id, aes.machine_alarm_type, aes.machine_alarm_no, aes.machine_alarm_axis, ad.alarm_msg_kr, sum(aes.holding_time) as total_holding_time, count(*) as cnt, date_format(aes.reg_date, '%Y-%m-%d') as date    \r\n" + 
//			"FROM                                                                                                                                                                                                                                                                   \r\n" +
//			"    factory f                                                                                                                                                                                                                                                          \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                   \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                                                                                          \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                   \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                                                                                         \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                   \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                                                                                       \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                   \r\n" +
//			"	alarm_event_status aes ON m.machine_id = aes.machine_id AND aes.reg_date > :startDate AND aes.reg_date < :endDate AND aes.update_date IS NOT NULL                                                                                                                                                     \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                   \r\n" +
//			"	alarm_dictionary ad ON aes.alarm_id = ad.alarm_id AND ad.use_yn = 'y'                                                                                                                                                                                                 \r\n" +
//			"JOIN                                                                                                                                                                                                                                                                   \r\n" +
//			"	alarm_type atp ON ad.alarm_type_id = atp.alarm_type_id AND atp.use_yn = 'y'                                                                                                                                                                                           \r\n" +
//			"WHERE                                                                                                                                                                                                                                                                  \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                                                                                                             \r\n" +
//			"    AND                                                                                                                                                                                                                                                                \r\n" +
//			"    (a.area_id = :areaId OR :areaId IS NULL)                                                                                                                                                                                                                           \r\n" +
//			"    AND                                                                                                                                                                                                                                                                \r\n" +
//			"    (m.machine_id = :machineId OR :machineId IS NULL)                                                                                                                                                                                                                  \r\n" + 
//			"    AND                                                                                                                                                                                                                                                                \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                                                                                    \r\n" +
//			"GROUP BY                                                                                                                                                                                                                                                               \r\n" +
//			"	m.machine_id, aes.alarm_id, date                                                                                                                                                                                                                                      \r\n" +
//			"ORDER BY                                                                                                                                                                                                                                                               \r\n" +
//			"	cnt desc, date                                                                                                                                                                                                                                                        \r\n")
//	List<Object[]> userFindAlarmDetailCntListByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate);
	
	// 알람 이력 조회
	// qeurydsl로 변경하여 주석 처리
//	@Query(nativeQuery = true, value =
//			"SELECT                                                                                                                                                                                             \r\n" +
//			"    a.area_id, a.area_name, m.machine_id, m.machine_name, aes.reg_date, aes.update_date, aes.alarm_id, aes.machine_alarm_type, aes.machine_alarm_no, aes.machine_alarm_axis, aes.alarm_msg, atp.alarm_type         \r\n" +  
//			"FROM                                                                                                                                                                                               \r\n" +
//			"    factory f                                                                                                                                                                                      \r\n" +
//			"JOIN                                                                                                                                                                                               \r\n" +
//			"	qg_client qc ON f.factory_id = qc.factory_id                                                                                                                                                      \r\n" +
//			"JOIN                                                                                                                                                                                               \r\n" +
//			"	machine m ON qc.qg_client_id = m.qg_client_id                                                                                                                                                     \r\n" +
//			"JOIN                                                                                                                                                                                               \r\n" +
//			"	area a ON m.area_id = a.area_id                                                                                                                                                                   \r\n" +
//			"JOIN                                                                                                                                                                                               \r\n" +
//			"	alarm_event_status aes ON m.machine_id = aes.machine_id AND aes.reg_date > :startDate AND aes.reg_date < :endDate                                                                                 \r\n" +
//			"JOIN                                                                                                                                                                                               \r\n" +
//			"	alarm_dictionary ad ON aes.alarm_id = ad.alarm_id AND ad.use_yn = 'y'                                                                                                                             \r\n" +
//			"JOIN                                                                                                                                                                                               \r\n" +
//			"	alarm_type atp ON ad.alarm_type_id = atp.alarm_type_id AND atp.use_yn = 'y' AND (atp.alarm_type_id = :alarmTypeId OR :alarmTypeId IS NULL)                                                                                                                       \r\n" +
//			"WHERE                                                                                                                                                                                              \r\n" +
//			"	f.factory_id = :factoryId                                                                                                                                                                         \r\n" +
//			"    AND                                                                                                                                                                                            \r\n" +
//			"    (a.area_id = :areaId OR :areaId IS NULL)                                                                                                                                                       \r\n" +
//			"    AND                                                                                                                                                                                            \r\n" +
//			"    (m.machine_id = :machineId OR :machineId IS NULL)                                                                                                                                              \r\n" +
//			"    AND                                                                                                                                                                                            \r\n" +
//			"    m.view_yn = 'y'                                                                                                                                                                                \r\n" +
//			"ORDER BY                                                                                                                                                                                           \r\n" +
//			"	m.machine_id, aes.reg_date asc, update_date asc                                                                                                                                                   \r\n" +
//			";                                                                                                                                                                                                  \r\n")
//	List<Object[]> userFindAlarmHistoryByFactoryIdAndAreaIdAndMachineIdAndRegDate(@Param("factoryId") Integer factoryId, @Param("areaId") Integer areaId, @Param("machineId") Integer machineId, @Param("startDate") String startDate, @Param("endDate") String endDate, @Param("alarmTypeId") Integer alarmTypeId);
}
